# emqx/Dockerfile
FROM emqx:4.4.3

ENV EMQX_DASHBOARD__DEFAULT_USER__LOGIN=labiot
ENV EMQX_DASHBOARD__DEFAULT_USER__PASSWORD=labiot

# Opcional: Si necesitas hacer alguna configuración adicional, puedes agregar más comandos aquí
