# grafana/Dockerfile
FROM grafana/grafana:8.5.3

# Configuración de las variables de entorno
ENV GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/admin_password

# Opcional: Si necesitas hacer alguna configuración adicional, puedes agregar más comandos aquí
